"""L3 line observability entrypoint generated by factory."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict


def observe_step(task_id: str, step_code: str, status: str, payload: Dict[str, Any]) -> Dict[str, Any]:
    """Return a normalized step observation event for line runtime."""
    return {
        "timestamp": datetime.now().isoformat(),
        "task_id": task_id,
        "step_code": step_code,
        "status": status,
        "payload": payload,
    }
