"""L3 line observability entrypoint generated by factory."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict

STEP_ERROR_CODE_CATALOG = {
  "INPUT_VALIDATION": {
    "error_code": "STEP_INPUT_VALIDATION_FAIL",
    "error_message": "输入验证 执行失败"
  },
  "ADDRESS_NORMALIZATION": {
    "error_code": "STEP_ADDRESS_NORMALIZATION_FAIL",
    "error_message": "地址标准化 执行失败"
  },
  "QUALITY_CHECK": {
    "error_code": "STEP_QUALITY_CHECK_FAIL",
    "error_message": "质量评估 执行失败"
  },
  "OUTPUT_PERSIST": {
    "error_code": "STEP_OUTPUT_PERSIST_FAIL",
    "error_message": "结果持久化 执行失败"
  },
  "DATA_GENERATION": {
    "error_code": "STEP_DATA_GENERATION_FAIL",
    "error_message": "数据生成 执行失败"
  }
}


def observe_step(
    task_id: str,
    step_code: str,
    status: str,
    payload: Dict[str, Any],
    error_code: str = "",
    error_detail: str = "",
) -> Dict[str, Any]:
    """Return normalized step observation event with standard error code."""
    step_key = str(step_code or "").upper()
    default_code = (STEP_ERROR_CODE_CATALOG.get(step_key) or {}).get("error_code", "")
    final_error_code = error_code or (default_code if status == "failed" else "")
    return {
        "timestamp": datetime.now().isoformat(),
        "task_id": task_id,
        "step_code": step_code,
        "status": status,
        "error_code": final_error_code,
        "error_detail": error_detail,
        "payload": payload,
    }
